### ISSUE TITLE
Keyboard Covers Alt Auth Link

### ISSUE THREAD

**Issue by redreceipt** [ApollosProject/apollos-apps#1045]
### User Story

As a user who changes their mind about how they want to sign in, I want to see the email/password login link even if the keyboard is open.

### Description

The keyboard on the mobile login screen covers the email/password login link.

![Kapture 2019-09-04 at 10 35 01](https://user-images.githubusercontent.com/2659478/64264807-e6763680-ceff-11e9-8fd6-708971529b64.gif)

### Acceptance Criteria

* [ ] It should [SPEC_DETAIL]

### Possible Implementation & Open Questions

Include it all in a `KeyboardAvoidingView`

### Other Resources

* Design mockup/prototype link
* Basecamp todo or link to "epic" on GitHub

**Comment by cdanwards** [comment]
@burkeshartsis @kevin-birdy would this be considered an intentional design? The drive is to have people log in with their phone number, and that is prioritized with the autofocus on the text input. The scrollview also allows for phones of differing sizes to look great on this screen. I tried messing around with a few ways to have the keyboardavoidingview not cover the alternate login link but none were great.
In essence, is this actually an issue?

**Comment by richarddubay** [comment]
Obviously I'll let others comment, but I _do_ think this is an issue. When someone first comes to this screen, the keyboard is already up and covering the username/password option. There is no indication that there is something else that you can scroll to and see to give the user another option to sign in. 

I don't think this is intentional, and honestly, if it is, then I think we need to rethink our intention. There's no sense in allowing the option to be there and then hiding it so no one can see it.

**Comment by cdanwards** [comment]
@richarddubay So this works within a ScrollView, so the link it's unreachable, it's just below the viewing threshold. If the view didn't autofocus to the keyboard, would that be a sufficient fix?

**Comment by kevin-birdy** [comment]
Here's a side by side of 5s vs. XR. Obviously a pretty significant difference and we're not going to be able to nail the smallest of devices 😅

I think @cdanwards has the easiest win by making it so that we don't autofocus the input. Feels like requiring all users to click the input is a small tradeoff for ensuring all users can see all available options regardless of device size.

![Image-1](https://user-images.githubusercontent.com/41083408/64704084-aec93a80-d47b-11e9-8759-835244f19e2d.jpg)
![IMG_6E192F2741BF-1](https://user-images.githubusercontent.com/41083408/64704094-b38dee80-d47b-11e9-81d3-e71d8ac661d5.jpeg)

**Comment by richarddubay** [comment]
I think not autofocusing the input is a good trade-off here. :shipit:

**Comment by kevin-birdy** [comment]
Samesies

**Comment by burkeshartsis** [comment]
It all depends on the accounts your actual users will use. We default to the text flow because we tested with users that it was the most effective and preferred. I login with email but I'm also not a user. Another thing we discussed was collecting phone numbers as a means of getting them/updating them in Rock even if they used to login via email. If they really want to use an email they can but I think the preference from the design sprint was text flow thus the auto focus.

**Comment by richarddubay** [comment]
@burkeshartsis Do you think that by taking away the auto-focus we lose the "preference" of getting them to enter their phone number? Like somehow a person would be less inclined to enter their phone number if the input wasn't auto-focused? On the small phones (as pictured above) you can't even see the input to put in your phone number.
