### ISSUE TITLE
Should Be Able to Close Fullscreen Player

### ISSUE THREAD

**Issue by redreceipt** [ApollosProject/apollos-apps#1065]
### User Story

As a user who's done watching a video, I want to be able to close the video without minimizing the mini-player because it's faster. And the alternative is unnecessary.

### Description

You currently have to make two clicks if you want to stop watching a video, one to minimize the player and then one to close. You should be able to close straight from the fullscreen player.

![File](https://user-images.githubusercontent.com/2659478/65273951-4ec43b00-daf0-11e9-9301-a0c1c5fc92b5.jpg)

### Why

It's faster and the alternative is unnecessary. 

### Acceptance Criteria

* [ ] It should add a close button to the fullscreen player.

### Other Resources

* Design mockup/prototype link
* Basecamp todo or link to "epic" on GitHub

**Comment by richarddubay** [comment]
I'd like to 👍 this. It seems unnecessary to have to minimize the video in order to close it.

**Comment by redreceipt** [comment]
@kevin-birdy can I ask the purpose of the "hide video" button in the bottom right? seems unnecessary. We could move airplay there and put a close button up top.

**Comment by kevin-birdy** [comment]
Ya, you guys are spot on. This has been kind of bugging me ever since weekend experience but it wasn't in scope so I didn't make any changes to this page.

What do you think about removing the volume and having that be 100% controlled by the hardware, and keeping the hide video button? That almost feels easier to remove to me. Then we could move airplay down bottom left, and have minimize top left, and exit top right. Also we can use our same modal circles with the icons in them (1- down-arrow + 2-'X') at the top.

Looping in @burkeshartsis as well to see if he has thoughts but I think this is a good idea.

**Comment by richarddubay** [comment]
@kevin-birdy I think these are great choices. Definitely love the "X" in the top right. Would love to see if this is something that we could work on sooner rather than later. We'd be willing to tackle it.

**Comment by kevin-birdy** [comment]
Ya that way this page will feel a bit more consistent I think. If you guys are willing to tackle it I feel like we could just greenlight swapping out the icons (nothing will change about placement or page layout) but I want to give @burkeshartsis or @vinnyjth  an opportunity to weigh in just in case I'm missing something.

**Comment by burkeshartsis** [comment]
FWIW, Youtube doesn't have any volume controls on its media player but they do have a two step close flow. My guess for the two steps is because it keeps people people engaged with content longer. But that's something we could test for ourselves. 

While I continue to fly two flags. If we ever wanted additional functionality on the fullscreen media player like comments, next steps, scripture references, jump to index (worship, teaching, announcements, etc.), related content, prayer, call to actions, etc. we would probably want a two step to close flow.

**Comment by redreceipt** [comment]
@burkeshartsis this did come from actual user feedback. If it's not enough to move the needle, I would love to be briefed on how much data is sufficient to make a decision.

**Comment by conrad-vanl** [comment]
This is coming in the media player rewrite
