### ISSUE TITLE
Rock Data Source : False positives on User Exists

### ISSUE THREAD

**Issue by asleepingpanda** [ApollosProject/apollos-apps#1979]
## What is the issue?
We've discovered an issue where the API is sending back a false positive on the `userExists` check. This is resulting in people being logged in to a user account with an incomplete Person being created. Specifically, First Name and Last Name are missing from the person record and the record ONLY contains the Phone Number

## How do I replicate?
Log in with a **_new phone number**_ so that the Person Details flow is triggered. 
Fill out the Personal Details in order to land on the Confirmation screen and wait until you get a Confirmation Code. 
**DO NOT** fill in the confirmation code, but instead close to App to "fall off" of the auth flow.
Open the app back up and fill in the phone number, again. This time, you should be taken straight to the Confirmation screen because you were falsely identified as an existing user.

## What do we do from here?
I think the issue is with [this line of code](https://github.com/ApollosProject/apollos-apps/blob/master/packages/apollos-data-connector-rock/src/auth/data-source.js#L133) because it's only checking for a User Name. I think this check needs to be more robust and include a check for a Person Id and then _also_ check that Person record for a First Name and Last Name.

**Comment by asleepingpanda** [comment]
I attempted the solution I suggested above on the CF api and it worked-ish. You're sent back through the User Details flow of a new user, but none of the user details you enter in get updated on the existing Person.

**Comment by conrad-vanl** [comment]
Do you have any data on how often this has happened for CF? It's definitely something we can/should fix but also feels very edge casey

**Comment by asleepingpanda** [comment]
Over this weekend, we pushed our Group Finder and almost 3% of our users who signed up for a Group experienced this bug.

**Comment by redreceipt** [comment]
Ok so problem restated:

1. we ask for a number
1b. we create a `UserLogin` in Rock with a null person
2. we ask for profile details, assuming `registerWithSms` will be called
3. user quits the app
4. user opens the app back and types in their number
5. since user login exists, we run `authenticateWithSms` instead which doesn't take profile info. we don't have it anymore anyway.
5b. person is created with just a phone number, no profile info

@vinnyjth @conrad-vanl we could do a couple of things here:

- we could go ahead and create the `Person` when we create the `UserLogin` and patch the person every time they push next. potentially dangerous because we could end with lots of partial people
- we could store the profile details with the number using async storage and then always call `registerWithSms` even if the login already exists. same problem would exist if the app were reinstalled in the flow.
- we could go back to how it was before, profile details _after_ login. the slides would only show if the info was incomplete.

no matter what, unfortunately we'll need a client side update because we're losing track their profile info if the flow is interrupted in any way.

**Comment by vinnyjth** [comment]
Option 4

- When creating a UserLogin, somehow mark it as incomplete. Don't consider that use login when running `userExists`. Mark that user as complete when they add a Person with first/last name

Option 5 

- I agree with Conrad that this is edgecasey. Wait until we migrate auth and stuff to Postgres. Fix it there.

**Comment by redreceipt** [comment]
actually option 4 might be pretty simple, if there's no personId on the userlogin, it's incomplete, essentially what Caleb said above. we would just need still delete and re-add.

**Comment by asleepingpanda** [comment]
> if there's no personId on the userlogin

@redreceipt there are 2 things that _could_ happen, here. Sometimes there is no PersonId, and sometimes a Person _is_ created, but First Name and Last Name are `null`. So, to mark a person as "incomplete", we would need to check both of these cases.

> Wait until we migrate auth and stuff to Postgres
@vinnyjth I understand why this would be the preferred approach and would probably agree with this being the "better" of the options presented. BUT, Christ Fellowship has a LOT of custom API resourcing and we will not be prepared to migrate our code to Postgres anytime soon. In our case, specifically, we will need to get this patched. If Core decides to go the approach of waiting util Postgres, I would just ask that we be notified ASAP so we can plan to patch this on our project directly.

**Comment by redreceipt** [comment]
No longer a core issue because we're making duplicates left and right thanks to the auth security patch.
