### ISSUE TITLE
Video Analytics

### ISSUE THREAD

**Issue by conrad-vanl** [ApollosProject/apollos-apps#2214]
Add analytics events to the core video player.

We should track data that allows us to see:

- Video URL, Content Title, Content Category/Channel watched
- Watch time (both total time and percentage of completion)

Some research might need to be done on video analytics best practices, as I'm going off of gut here, but I think we could do this via these events:

- `WatchMediaStart` Video URL, Content Title, Content Category/Channel
- `WatchMediaStop` Duration, % complete

With that said, triggering WatchMediaStop might be difficult. It would likely need to be triggered on `componentWillUnmount` to handle most edge-cases (such as navigating away in the middle of a video). 

We could also have a polling-type event `WatchMediaProgress` that triggers every 5 seconds or something while someone is watching. I'm not a fan of the # of events that would get tracked though with this (we pay per event with most analytics services)

**Comment by camrun91** [comment]
@conrad-vanl may look at Rock core I think it is v13 they are doing this with the rock player in their mobile apps as well. I do not know how but they are also making it so that if you start a video on a rock mobile app you can stop it then log into the website and pick up right where you left off. I do not know if there is anything there that we could leverage. 

They talked about it at the rock conference

**Comment by tomthornton** [comment]
@conrad-vanl I think this will be fairly easy to track. Right now the `isPlaying` and `elapsedTime` state is available which makes this pretty straight forward. Instead of `componentWillUnmount` we'll just need to return a cleanup function in `useEffect`.

I'm wondering if we should go ahead and implement video progress that @camrun91 was talking about into the PR for this issue. That way we can have users resume where they started and also send more accurate analytics such as `WatchedMedia` that includes the user, video, start time and stop time. We can just use the interactions table that we already have.

**Comment by camrun91** [comment]
@conrad-vanl yes I think a separate pr/issue would be good. I have no idea how Rock is doing it and if they have rolled it out yet. I assume that it is active to some level in the dev branch of rock. I would assume they are using Rock interactions for it so leveraging shovel to keep that particular one in sync could be interesting.

**Comment by camrun91** [comment]
This would be a huge win for us as well.
