### ISSUE TITLE
Implement Chromecast

### ISSUE THREAD

**Issue by redreceipt** [ApollosProject/apollos-apps#448]
## TODO

- [ ] Needs design
- [ ] Needs library verification

## User Story

As a `<type of user>` _(who)_ I want to `<perform an action>` _(what)_ so that I can `<achieve a goal>` _(why)_.

#### Problem Details _(Optional)_

* split out from #250
* Screenshots, GIFs, or a video
* Any additional information (version, device, etc.)

#### Acceptance Criteria _(Optional)_

* [ ] It should [SPEC_DETAIL]

**Comment by redreceipt** [comment]
@conrad-vanl @kevin-birdy what do you think about this for MVP

![Component 1](https://user-images.githubusercontent.com/2659478/77018596-6c197b00-6954-11ea-9c74-6b34eaddf2fc.png)

**Comment by kevin-birdy** [comment]
@redreceipt how are you displaying that when the phone is flipped?

**Comment by redreceipt** [comment]
![Component 2](https://user-images.githubusercontent.com/2659478/77018930-90c22280-6955-11ea-8fb5-751ddd8b2936.png)

**Comment by kevin-birdy** [comment]
![Group 2](https://user-images.githubusercontent.com/41083408/77019078-489b0400-6945-11ea-8572-a96c97cdaaeb.png)
Ok just wanted to make sure. The only other option I see is grouping the icons top right. This would be nicer when the phone is flipped, but you'd have to more quickly truncate titles so I'm not convinced it's actually an improvement 🤔

**Comment by redreceipt** [comment]
down below would allow us to add a "close" button up top, a requested feature from some of our users (and a personal minor frustration of mine)

**Comment by kevin-birdy** [comment]
Makes sense :)

**Comment by conrad-vanl** [comment]
What's the difference between close and minimize? I would warn that that could get confusing for the people that aren't complaining about the current setup.

As far as these buttons go... what I'd love to do is have a single airplay/cast button (maybe we design our own) that opens up a menu that allows you to pick between Chromecast and AirPlay, and actually use those words, instead of relying on users to know the difference between an airplay logo and a chromecast logo.

A step above that even would be mimicking something like what Spotify does - they have a combined icon that when you tap on it it immediately shows Chromecast devices, with an "AirPlay or Bluetooth" option at the end (in reality, the airplay button also shows bluetooth devices)/ The Youtube app also does something similar - they use a single chromecast logo on top of the player, but when you tap on it it opens a contextual menu with cast devices listed, and a "AirPlay and Bluetooth Devices" option.

**Comment by conrad-vanl** [comment]
Also @redreceipt for MVP I'm also 100% fine with the screenshots you linked. I might want @kevin-birdy to play around with spacing / sizing / opacity to see if we can improve it any. But if that's where we start, then this is still great.

**Comment by kevin-birdy** [comment]
Not a whole lot of suggestions. I agree about the opacity as we want these to be secondary actions to pause for example. So I am using 50% opacity (alpha-300).  32px feels like a nice tappable area. As far as spacing goes, I am using 32px right now (looks like maybe you have 64px in your mockup). It's a small tweak but my preference is slightly more condensed.

![Placement](https://user-images.githubusercontent.com/41083408/77085996-ba676200-69c6-11ea-9fe1-eb72b1adbaad.png)

**Comment by conrad-vanl** [comment]
Could we get the icons so that the "squares" / frames in each of the icons were the same size and lined up? It feels like the airplay/apple tv logo is up higher then the chromecast one

**Comment by kevin-birdy** [comment]
@redreceipt can I ask where you got the Airplay icon from? The reason they are different is I was actually just using an icon font from SF Symbols which isn't going to match up perfectly and doesn't give us much control. So I am actually just manipulating the font size to get as close as I can.

<img width="1049" alt="Screen Shot 2020-03-19 at 5 25 28 PM" src="https://user-images.githubusercontent.com/41083408/77123766-ae9b9000-6a06-11ea-90fc-4d7f36f5c57c.png">

**Comment by redreceipt** [comment]
Google search. I'm assuming the RN packages will have icons that I can
adjust the size (not sure about transparency) and I'll just top-align them
to make the boxes the same size.


--
Michael Neeley
Junior Web Developer
NewSpring Church
www.newspring.cc
Cell: (803) 622-6599

**Comment by kevin-birdy** [comment]
Ok hah. I couldn't find an official one that wasn't SF Symbols :) Ya your icons are going to be more realistic anyway than. As long as they are the same size they should work great and if you can update the opacity too that is definitely a +1 👍
