### ISSUE TITLE
The primary button is super low in the select campus screen on iPhone XR

### ISSUE THREAD

**Issue by vinnyjth** [ApollosProject/apollos-apps#943]
### Apollos Version: x.x.x

![image](https://user-images.githubusercontent.com/1637694/62225083-c514ae80-b385-11e9-8f9b-d44cc5a35af4.png)

### Details

On the iPhone XR, the "select campus" screen has a very small margin between the button and the bottom of the screen. The button might need to be wrapped in a SafeAreaView. 

### Possible Fix

<details><summary>Additional Info</summary>

### Your Environment

- Environment name and version (e.g. Chrome 39, node.js 5.4):
- Operating System and version (desktop or mobile):
- Link to your project:

### Steps to Reproduce

1.  first...
2.
3.
4.

### Stack Trace

</details>

**Comment by conrad-vanl** [comment]
We should also double check that this is still an issue when you boot the app without storybook. I've noticed storybook has been messign with our `SafeAreaView`, and in a few new components I had to default back to using `react-navigation`'s `SafeAreaView` instead of `react-native`'s for it to work :/
